[project]
name = "who-life-expectancy"
version = "0.1.0"
dependencies = [
    "numpy",
    "pandas",
    "statsmodels",
    "scikit-learn",
    "seaborn",
    "streamlit",
    "matplotlib",
    "kagglehub",
    "python-dotenv",
]

[tool.setuptools]
packages = ["utils"]

[tool.black]
line-length = 100
